<?php
define("_ACCASSCAT", "Acct. Assigt. Cat.");
define("_ADDFAVORITELIST", "Add Favorite List");
define("_ADDITEM", "Add Item");
define("_ADDNEW", "Add New");
define("_ADDNEWSAPSYSTEM", "Add New SAP System");
define("_ADDRESNOTFOUND", "Address Not Found");
define("_AGINGINFORMATION", "AR Aging Information");
define("_ALERT", "Alert");
define("_ALLFIELDSMANDATORY", "All fields are mandatory.");
define("_ALLITEMS", "All Items");
define("_ALREADYEXIST", "already exist");
define("_AMOUNT", "Amount");
define("_AMOUNTDUE", "Amount Due");
define("_APPLICATIONSERVER", "Application Server");
define("_APPROVECONVERTTOPO", "Approve / Convert to PO");
define("_APPROVECUSTOMERSMASTER", "Approve Customers Master");
define("_APPROVEPURCHASEORDER", "Approve Purchase Order");
define("_AUTHTYPE", "Auth Type");
define("_AVAILANLESAPSYSTEM", "Available SAP Systems");
define("_BACK", "Back");
define("_BAPIVERSION", "bapi version");
define("_BILLINGLIST", "Billing List");
define("_BIREPORTS", "BI Reports");
define("_BOBJSYSTEMURL", "BOBJ System URL");
define("_CANCEL", "Cancel");
define("_CHANGEPASS", "Change Password");
define("_CHANGENEWPURCHASEREQUISITION", "Change Purchase Requisition");
define("_CHECK_RETURN_STATUS", "Check Returns Status -Admin");
define("_CITY", "City");
define("_CLICKTOCONFIRM", "Click to Confirm");
define("_CMSNAME", "CMS Name");
define("_CMSPORT", "CMS Port");
define("_COMINGSOON", "Coming Soon.........");
define("_COMMISSIONREPORT", "Commission Report");
define("_COMPANYADDRESS", "Company Address");
define("_COMPANYCODE", "Company Code");
define("_COMPANYNAME", "Company Name");
define("_CONFIRMPASS", "Confirm password");
define("_CONFIRMPRODORDER", "Confirm Prod Order");
define("_CONNECTIONTYPE", "Connection type");
define("_COPYSALESQUOTATION", "Copy Sales Quotation");
define("_COSTCENTER", "Cost Center");
define("_COUNTRY", "Country");
define("_CREATECOSTCENTERMASTER", "Create Cost Center Master");
define("_CREATECUSTOMERS", "Crear clientes");
define("_CREATECUSTOMERSMASTER", "Create Customers Master");
define("_CREATEDELIVERY", "Create Delivery");
define("_CREATEDSUCCESS", "Created Successfully<br>");
define("_CREATENEWPURCHASEREQUISITION", "Create Purchase Requisition");
define("_CREATEPRODORDER", "Create Prod Order");
define("_CREATEPURCHASEORDER", "Create Purchase Order");
define("_CREATEPURCHASEREQUISITION", "Create Purchase Requisition");
define("_CREATESALESORDER", "Create Sales Order");
define("_CREATESALESQUOTATION", "Create Sales Quotation");
define("_CREATESALESQUOTATIONSOLD", "Create Sales Quotation Sold");
define("_CREDITCONTROLAREA", "Credit Control Area");
define("_CREDITLIMIT", "Credit Limit");
define("_CURRENCY", "Currency");
define("_CUSTOMERDETAILS", "Customer Details");
define("_CUSTOMERNAME", "Customer Name");
define("_CUSTOMERNUMBER", "Customer Number");
define("_CUSTOMEROPENITEMS", "Customer Open Items");
define("_CUSTOMEROPENITEMSHEAD", "Customer Open Items Head");
define("_CUSTOMERORDERS", "Customer Orders");
define("_CUSTOMERPO", "Customer PO number");
define("_CUSTOMERPONO", "Customer PO number");
define("_CUSTOMIZE", "Customize");
define("_CUSTOMPPLICATIONSERVER", "Custom Application server");
define("_CUSTOMSCCEHULINGREPORT", "Custom Scheduling Report");
define("_DASHBOARDINVOICED", "Dashboard: Invoiced Sales by Region by Customer");
define("_DASHBOARDSALES", "Dashboard: Sales Order Dashboard");
define("_DELETE", "Delete ");
define("_DELETEITEM", "Delete Item");
define("_DELIVDATE", "Delivery Date");
define("_DELIVERYLIST", "Delivery List");
define("_DEMOSYSTEM", "Demo System");
define("_DESCRIPTION", "Description");
define("_DETAILS", "Details");
define("_DIRECTIONS", "Directions");
define("_DISCOUNT", "Discount");
define("_DISPLAYANDEDITVENDOR", "Display and Edit Vendor");
define("_DISPLAYBILLINGDOCUMENT", "Display Billing Document");
define("_DISPLAYEDITCUSTOMER", "Display and Edit Customer");
define("_DISPLAYLISTAPPROVE", "Display List/Approve");
define("_DISPLAYPURCHASEORDER", "Display Purchase Order");
define("_DISPLAYSALESORDER", "Display Sales Order");
define("_DISPLAYSALESQUOTATION", "Display/Edit Sales Quotation");
define("_DISTRIBUTIONCHANNEL", "Distribution Channel");
define("_DIVISION", "Division");
define("_DOCUMENTBEINGEMAILED", "This Document is being emailed upon request by");
define("_DOCUMENTFLOW", "Document Flow");
define("_DOCUMENTNUMBER", "Document Number:");
define("_Done", "Done");
define("_EDIT", "Edit");
define("_EDITCOSTCENTERMASTER", "Edit Cost Center Master");
define("_EDITCUSTOMERMASTER", "Edit Customer Master");
define("_EDITCUSTOMERS", "Edit Customers");
define("_EDITSALESQUOTATIONSOLD", "Edit Sales Quotation Sold");
define("_ENGLISH", "English");
define("_ENTERNEWPASS", "Enter new password");
define("_ENTEROLDPASS", "Enter old password");
define("_ERROR_MANY_COLUMNS", "<script type='text/javascript'>alert('There are too many columns to produce a readable PDF. Please use Excel/CSV download.');</script>");
define("_ERRORCONECTIONSAP", "There was an error connecting to your SAP System.<br> Please check your Systems Settings, Client, Username and Password or contact us.");
define("_ERRORMESSAGE", "Error Message");
define("_EXCEPTIONRAISED", "Exception raised:");
define("_EXPORT", "Export");
define("_EXPORTALL", "Export All");
define("_EXPORTVIEW", "Export View");
define("_EXTENDED", "Extended");
define("_FAVORITE", "Favorite");
define("_FAVORITELIST", "Favorite List");
define("_FAVORITESNOTFOUND", "Favorites not found");
define("_FILTER", "Filter");
define("_FILTERS", "Filters");
define("_FINANCE", "Finance");
define("_FINANCECONTROLLING", "Finance and Controlling");
define("_FIXEDAMOUNT", "Fixed amount");
define("_FORECASTSTOCK", "Forecast to Stock");
define("_FREEGOODS", "Free goods");
define("_FROMDATE", "From Date");
define("_GIVEPASSWORDHERE", "Given password here will not be saved, it will be used only to validate the system.");
define("_GLACCOUNT", "GL Account");
define("_GROUP", "Group");
define("_GROUPSERVERSELECTION", "Group/server selection");
define("_HAVEUPDATESUCCESS", "You have updated successfully");
define("_HEADERNOTE", "Header Note");
define("_HEADERTXT", "Header Text");
define("_HELP", "Help");
define("_HIGHTITEM", "High level item");
define("_HISTORY", "History");
define("_HISTORYNOTFOUND", "History not found");
define("_HOUSENO", "House No");
define("_INSTANCENUMBER", "Instance Number");
define("_INVALIDOLDPASS", "Antigua Contraseña Invalida");
define("_INVENTORY", "Inventory");
define("_ITEM", "Item");
define("_ITEMS", "Items");
define("_ITEMTXT", "Item Text");
define("_KEYDATE", "Key Date");
define("_LANGUAGE", "Language");
define("_LASTNAME", "Last Name");
define("_LICENSEINFO", "License Info");
define("_LISTSALES", "List of Sales Orders with Credit Block");
define("_LOGOUT", "Logout");
define("_MAILERERROR", "Mailer Error");
define("_MASTER_DATA", "Master Data");
define("_MATERIAL", "Material");
define("_MATERIALAVAILABILITY", "Material Availability");
define("_MATERIALTRANSFER", "Material Transfer");
define("_MESAGGESERVER", "Message Server");
define("_MESSAGE", "Message");
define("_MESSAGESENT", "Message has been sent");
define("_MORETHEN120DAY", "More Then 120 Days");
define("_MULTISORT", "Multi Sort");
define("_NAME", "Name");
define("_NETVALUES", "Net Values");
define("_NEXT", "Next");
define("_NOHEADERNOT", "No of Headers Not valid");
define("_NOITEMFOUND", "No Items Found");
define("_NOMACHESFOUND", "No maches found near by");
define("_NONE", "None");
define("_NORECORDS", "No Records Found");
define("_NOSYSTEM", "NOSYSTEM");
define("_NOTCONFIGFOLDER", "is not Available in Config folder.");
define("_NOTEFILTER", "Note : Use at least one filter for fast search results");
define("_NOTEIDCOMPLETED", "Note: If SSO setup is completed by deploying BOBJSession web service in your company BOBJ system you can select extended check box above.");
define("_NOTEPLEASEURLFORMAT", "Note: Please give URL with following format:");
define("_NUMBERCOLUMS", "Number of Columns");
define("_ONEITEMREQUIRED", "<b>At least one item is required.</b>");
define("_OPENITEMS", "Open Items");
define("_OR", "or");
define("_ORDERCASH", "Order to Cash");
define("_ORDERQUANTITY", "Order Quantity");
define("_PAYMENTTERMCODE", "Payment Term Code");
define("_PAYMENTTERMDESC", "Payment Term");
define("_PAYMENTTERMS", "Payment Terms");
define("_PAYMENTTERMSDESC", "Payment Terms Desc.");
define("_PERCENTAGE", "Percentage");
define("_PERUNIT", "Per Unit");
define("_PHONE", "Phone");
define("_PICKANDPOSTGOODS", "Pick And Post Goods");
define("_PICKINGANDPOSTESIGN", "Picking And Post Esign");
define("_PICKINGPOST", "Picking And Post Goods Issue");
define("_PLACEINSTORAGE", "Place In Storage");
define("_PLANT", "Plant");
define("_PLEASEEDITSALESQUOTATION", "Please Edit the sales quotation in SAP GUI and complete the incompletions.");
define("_PLEASEFINDATTACHMENT", "Please find the attachment of");
define("_PLEASEPROVIDEUSERID", "Please Provide UserId or From and ToDate");
define("_PORCUREPAY", "Procure to Pay");
define("_POSTALCODE", "Postal Code");
define("_POSTGOODSRECEIPT", "Post Goods Receipt");
define("_POSTINCOMINGPAYMENT", "Post Incoming Payment");
define("_POSTINGDATE", "Posting To Date");
define("_PREVIOUS", "Previous");
define("_PRICEUNIT", "Price Unit");
define("_PRICINGUNIT", "Pricing unit");
define("_PRNOTEXISTS", "Purchase requisition doesn't exist.");
define("_PROCUREMENT", "Procurement");
define("_PRODUCTAVAILABILITY", "Product Availability");
define("_PRODUCTAVAILABILITYQUOTATION", "Product Availability Quotation");
define("_PRODUCTION", "Production");
define("_PRODUCTIONORDERCOSTING", "Production Order Costing");
define("_PRODUCTIONWORKBENCH", "Production Workbench");
define("_PROFILE", "Profile");
define("_PRTYPE", "PR Document Type");
define("_PRNUMBER", "PR Number");
define("_PURCHASEREQUISITIONNUMBER", "Purchase Requisition Number");
define("_PURGROUP", "Purchase Group");
define("_QUANTITY", "Quantity");
define("_QUOTATIONFROMDATE", "Quotation From Date");
define("_QUOTATIONMAILSUBJECT", "Sales Quotation Document from ThinUI");
define("_QUOTATIONPDFMAIL", "Sales_Quotation_Confirmation_");
define("_QUOTATIONTODATE", "Quotation To Date");
define("_REFRESHPAGE", "If you refresh the page, you will see that records will stay just as you modified.");
define("_RELEASEPRODORDER", "Release Prod Order");
define("_REMOVE", "Remove");
define("_REPORTS", "Reports");
define("_REQITEM", "Req. Item");
define("_REQPRICE", "Req. Price");
define("_REQUIREDFIELD", "Required Field");
define("_REVIEWSTATUSCUSTOMERSMASTER", "Review Status Customers Master");
define("_ROLE", "Role");
define("_ROUTERIP", "Router IP");
define("_ROUTERPORT", "Router Port");
define("_SALEORDERNUMBER", "Sale Order Number");
define("_SALEQUOTATIONNUMBER", "Sale Quotation Number");
define("_SALES", "Sales");
define("_SALESDOC", "Sales organization should not be empty");
define("_SALESDOCNOTCOMPLETE", "The sales document is not yet complete: Edit data ");
define("_SALESDOCTYPE", "Sales Document Type");
define("_SALESDOCUMENT", "Sales Document");
define("_SALESORDER", "Sales Order");
define("_SALESORDERCREDIT", "Sales Order Credit Release");
define("_SALESORDERCREDITBLOCK", "Sales Order Credit Block");
define("_SALESORDERDASHBOARD", "Sales Dashboard");
define("_SALESORDERREPORT", "Sales Order Report");
define("_SALESORGANIZATION", "Sales Organization");
define("_SALESPERSON", "Sales Person");
define("_SALESPRICE", "Sales Price");
define("_SALESQUOTATION", "Sales Quotation");
define("_SALESQUOTATIONCHANGE", "Sales Quotation Change");
define("_SALESQUOTATIONNOEXIST", "Sales quotation doesn't exist.");
define("_SALESTXT", "Sales Text");
define("_SALESWORKBENCH", "Sales Workbench");
define("_SAPSYSTEMMESSAGE", "SAP System Message");
define("_SAPSYSTEMMESSAGECS", "Changed Successfully");
define("_SAVE", "Save");
define("_SAVECHANGES", "Save changes");
define("_SAVECUSTOMIZE", "Save Customize");
define("_SEARCHCUSTOMERS", "Search Customers");
define("_SEARCHNEARBY", "Search nearby");
define("_SEARCHNEWPURCHASEREQUISITION", "Search Purchase Requisition");
define("_SEARCHPURCHASEORDERS", "Search Purchase Orders");
define("_SEARCHPURCHASEREQUISITION", "Search Purchase Requisition");
define("_SEARCHSALESORDERS", "Search Sales Orders");
define("_SEARCHSALESQUOTATION", "Search Sales Quotation");
define("_SEARCHTERM", "Search Term");
define("_SEARCHVENDORS", "Search Vendors");
define("_SELECTAMATERIAL", "Please select a material first");
define("_SELECTAUTHTYPE", "Select Auth Type");
define("_SELECTCONNECTIONTYPE", "Select the connection type");
define("_SELECTCOUNTRY", "Select Your Country");
define("_SELECTCUSTOMER", "Please select a customer first");
define("_SELECTITEM", "Select item");
define("_SELECTLANGUAGE", "Select Your Language");
define("_SELECTMATERIALFIRST", "You Have to Select Material First");
define("_SELECTPLANT", "Please select a plant");
define("_SELECTSYSTEMTYPE", "Select System Type");
define("_SENDEMAIL", "Send Mail");
define("_SENDMAIL", "Send as Mail");
define("_SHIPPARTY", "Ship To Party");
define("_SHOWMORE", "Show More");
define("_SOLDPARTY", "Sold To Party");
define("_SOLDPARTYNAME", "Sold To Party Name");
define("_SORT", "Sort");
define("_SPECIALCARACTERS", "Your string has special characters. \\nThese are not allowed.");
define("_STATE", "State");
define("_STORELOC", "Storage Location");
define("_STREET", "Street");
define("_STREETADDRESS", "Street Address");
define("_SU", "SU");
define("_SUBMIT", "Submit");
define("_SUCCESSMESSAGE", "Success message");
define("_SUMNETVALUES", "Sum of Netvalues");
define("_SUPPLYLIST", "Supply List");
define("_SWIPESCROLL", "Swip to Scroll");
define("_SYSTEMID", "System ID");
define("_SYSTEMS", "Systems");
define("_SYSTEMURL", "System URL");
define("_SYSTEMWITH", "System with");
define("_TABLECOLUMS", "Table columns");
define("_TECHNICALNAMES", "Technical Names");
define("_TIME_RECORDING", "Time recording");
define("_TIMERECORDING", "Time Recording");
define("_TODATE", "To Date");
define("_UOM", "Unit of Measure");
define("_UPTO120DAY", "Upto 120 Days");
define("_UPTO1DAY", "Upto 1 Day");
define("_UPTO30DAY", "Upto 30 Days");
define("_UPTO60DAY", "Upto 60 Days");
define("_UPTO90DAY", "Upto 90 Days");
define("_URLNOTWORKING", "URL_NOT_WORKING");
define("_VALIDFROMDATE", "Valid From Date");
define("_VALIDTODATE", "Valid To Date");
define("_WELCOME", "Welcome");
define("_ZREPORTS", "ZReports");
?>